// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro_De_Permisos.DAL;

namespace Registro_De_Permisos.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210220091846_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Registro_De_Permisos.Entidades.Permiso", b =>
                {
                    b.Property<int>("permisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("permisoId");

                    b.ToTable("Permiso");

                    b.HasData(
                        new
                        {
                            permisoId = 1,
                            descripcion = "Descuenta"
                        },
                        new
                        {
                            permisoId = 2,
                            descripcion = "Vende"
                        },
                        new
                        {
                            permisoId = 3,
                            descripcion = "Cobra"
                        });
                });

            modelBuilder.Entity("Registro_De_Permisos.Entidades.Roles", b =>
                {
                    b.Property<int>("rolesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("esActivo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("TEXT");

                    b.HasKey("rolesId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Registro_De_Permisos.Entidades.RolesDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermisoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rolid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("esAsignado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("rolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("rolesId");

                    b.ToTable("RolesDetalle");
                });

            modelBuilder.Entity("Registro_De_Permisos.Entidades.Usuarios", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Clave")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("RolId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RolesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UsuarioId");

                    b.HasIndex("RolesId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Registro_De_Permisos.Entidades.RolesDetalle", b =>
                {
                    b.HasOne("Registro_De_Permisos.Entidades.Roles", null)
                        .WithMany("RolesDetalle")
                        .HasForeignKey("rolesId");
                });

            modelBuilder.Entity("Registro_De_Permisos.Entidades.Usuarios", b =>
                {
                    b.HasOne("Registro_De_Permisos.Entidades.Roles", "rol")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("Registro_De_Permisos.Entidades.Roles", b =>
                {
                    b.Navigation("RolesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
